[main]
summary=NVIDIA Generic GPU Profile - baseline tuning when accelerator, intent, and service are not specified

[cpu]
governor=performance

[bootloader]
cmdline_init_on_alloc=init_on_alloc=0
cmdline_iommu=iommu=pt
cmdline_console=console=tty0 console=ttyS0,115200n8
cmdline_pci=pci=realloc=off

[sysctl]
vm.swappiness=1
net.core.netdev_max_backlog=10000
net.ipv4.tcp_max_syn_backlog=8192
net.ipv4.tcp_congestion_control=bbr
net.core.default_qdisc=fq
