#!/bin/bash

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Writes /etc/default/grub.d/99_tuned.cfg which sources /etc/tuned/bootcmdline.
# This makes `[bootloader]` stanzas in tuned profiles take effect on Ubuntu
# (which uses update-grub + /etc/default/grub.d rather than tuned's default
# /etc/default/grub rewrite).

set -e

BOOTCMDLINE_FILE="/etc/tuned/bootcmdline"
GRUB_D_DIR="/etc/default/grub.d"
GRUB_CONFIG_FILE="${GRUB_D_DIR}/99_tuned.cfg"

mkdir -p "$GRUB_D_DIR"

cat <<EOF > "$GRUB_CONFIG_FILE"
# This file is auto-generated by the nvidia-tuned service profile bootloader script
# It sources bootloader settings from /etc/tuned/bootcmdline when grub is configured

if [ -f "$BOOTCMDLINE_FILE" ]; then
    . $BOOTCMDLINE_FILE
    GRUB_CMDLINE_LINUX_DEFAULT=" \${TUNED_BOOT_CMDLINE}"
fi
EOF

chmod a+x "$GRUB_CONFIG_FILE"
update-grub

echo "Created grub configuration: $GRUB_CONFIG_FILE"
echo "This file will source $BOOTCMDLINE_FILE when grub is configured"
