#!/bin/bash

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Ubuntu: wire GRUB to apply tuned bootloader cmdline via /etc/tuned/bootcmdline.
# Enterprise Linux: tuned applies boot settings without this helper; skip.

set -e

if [ ! -f /etc/os-release ]; then
	exit 0
fi
# shellcheck source=/dev/null
. /etc/os-release
if [ "${ID:-}" != "ubuntu" ]; then
	echo "bootloader.sh: skipping GRUB drop-in (not Ubuntu, ID=${ID:-unknown})"
	exit 0
fi

BOOTCMDLINE_FILE="/etc/tuned/bootcmdline"
GRUB_D_DIR="/etc/default/grub.d"
GRUB_CONFIG_FILE="${GRUB_D_DIR}/99-nvidia-tuned-oke-tuned-bootcmdline.cfg"

mkdir -p "$GRUB_D_DIR"

cat <<EOF > "$GRUB_CONFIG_FILE"
# Auto-generated by nvidia-tuned OKE profile (bootloader.sh)

if [ -f "$BOOTCMDLINE_FILE" ]; then
	. $BOOTCMDLINE_FILE
	GRUB_CMDLINE_LINUX_DEFAULT="\${GRUB_CMDLINE_LINUX_DEFAULT} \${TUNED_BOOT_CMDLINE}"
fi
EOF

chmod a+x "$GRUB_CONFIG_FILE"

if [ -n "${SKIP_SYSTEM_OPERATIONS:-}" ]; then
	echo "bootloader.sh: SKIP_SYSTEM_OPERATIONS set; skipping update-grub"
else
	if ! command -v update-grub >/dev/null 2>&1; then
		echo "bootloader.sh: update-grub not found in PATH (install grub-pc or grub-efi-amd64)" >&2
		exit 1
	fi
	update-grub
fi

echo "Created $GRUB_CONFIG_FILE (sources $BOOTCMDLINE_FILE)"
